# Generated by Django 4.0.2 on 2022-02-17 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0003_blogheading'),
        ('MainApp', '0012_succcessfulclientheading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('project_url', models.URLField(blank=True, max_length=250, null=True)),
                ('short_description', models.TextField(blank=True, default='', null=True)),
                ('image', models.ImageField(upload_to='project')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='project')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('complete_data', models.DateField(blank=True, null=True)),
                ('billing_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('view_count', models.BigIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('facebook', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('twitter', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('youtube', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('linkedin', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.client')),
                ('tags', models.ManyToManyField(blank=True, to='blog.Tags')),
            ],
        ),
    ]
