# Generated by Django 4.0.2 on 2022-02-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjecctHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=250, null=True)),
                ('sub_title', models.TextField(blank=True, max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
