# Generated by Django 4.0.2 on 2022-02-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projecctheading'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjecctHeading',
            new_name='ProjectHeading',
        ),
    ]
