# Generated by Django 4.0.2 on 2022-02-10 05:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=50, region=None)),
                ('email', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('title', models.CharField(default='Bit Spirits Ltd. || Your best choice', max_length=250)),
                ('sub_title', models.CharField(blank=True, max_length=250, null=True)),
                ('about', models.TextField()),
                ('descriptions', models.TextField(default='', max_length=1000)),
                ('fav_icon', models.ImageField(upload_to='company')),
                ('header_logo', models.ImageField(blank=True, null=True, upload_to='company')),
                ('footer_logo', models.ImageField(blank=True, default='', null=True, upload_to='company')),
                ('facebook', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('twitter', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('youtube', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('linkedin', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('google_map_url', models.URLField(blank=True, default='', null=True)),
                ('video_img', models.ImageField(blank=True, default='', null=True, upload_to='company')),
                ('opening_day', models.CharField(blank=True, choices=[('saturday', 'Saturday'), ('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=250, null=True)),
                ('opening_time', models.TimeField(blank=True, max_length=50, null=True)),
                ('video', models.URLField(blank=True, default='', max_length=250, null=True)),
                ('holiday', models.CharField(blank=True, choices=[('saturday', 'Saturday'), ('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], default='', max_length=250, null=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('fast_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
                ('img', models.ImageField(default='', upload_to='user')),
                ('password', models.CharField(max_length=90)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
