# Generated by Django 4.0.2 on 2022-02-10 05:41

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_companyinfo_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='alt_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=50, null=True, region=None),
        ),
    ]
