# Generated by Django 4.0.2 on 2022-02-10 05:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_companyinfo_alt_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='holiday',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('saturday', 'Saturday'), ('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], default='', max_length=100, null=True),
        ),
    ]
