# Generated by Django 4.0.2 on 2022-02-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_companyinfo_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='website',
            field=models.URLField(blank=True, default='https://bitspirits.io/', null=True),
        ),
    ]
