# Generated by Django 4.0.2 on 2022-02-10 06:26

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_companyinfo_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=50, region=None)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('is_response', models.BooleanField(default=False)),
            ],
        ),
    ]
