# Generated by Django 4.0.2 on 2022-02-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_testimonialheading'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialheading',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
