# Generated by Django 4.0.2 on 2022-02-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_succcessfulclientheading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonialheading',
            old_name='heading',
            new_name='title',
        ),
        migrations.AddField(
            model_name='testimonialheading',
            name='sub_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
