# Generated by Django 4.0.2 on 2022-02-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_homebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('sub_title', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='why_choose_us/')),
                ('bg_image', models.ImageField(upload_to='why_choose_us/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
