# Generated by Django 4.0.2 on 2022-02-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0017_brands_delete_succcessfulclientheading'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='BrandHeading',
        ),
    ]
