# Generated by Django 4.0.2 on 2022-02-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_servicesection_sub_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True, max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250)),
                ('icon', models.ImageField(upload_to='services/')),
                ('bg_image', models.ImageField(upload_to='services/')),
                ('description', models.TextField(max_length=250)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
