# Generated by Django 4.0.2 on 2022-02-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_serviceheading_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
