# Generated by Django 4.0.2 on 2022-02-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_services_bg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
