# Generated by Django 4.0.2 on 2022-02-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_servicerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='num_project',
            field=models.IntegerField(),
        ),
    ]
