# Generated by Django 4.0.2 on 2022-02-17 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_features_whychooseus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePriceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services/icon/')),
                ('is_popular', models.BooleanField(default=True)),
                ('is_recomended', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Price Categories',
            },
        ),
        migrations.CreateModel(
            name='ServicePriceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePricePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('package', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('anully', 'Anully')], max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('features', models.ManyToManyField(blank=True, to='service.ServicePriceFeature')),
                ('price_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicepricecategory')),
            ],
        ),
    ]
