# Generated by Django 4.0.2 on 2022-02-20 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_whychooseus_sub_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceSection',
        ),
    ]
