# Generated by Django 4.0.2 on 2022-02-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_delete_servicesection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceRecord',
        ),
    ]
