# Generated by Django 4.0.2 on 2022-02-20 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_delete_servicerecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhyChooseUs',
        ),
    ]
