# Generated by Django 4.0.2 on 2022-02-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_delete_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectQuotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=250)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
