# Generated by Django 4.0.2 on 2022-02-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=255)),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('secondary_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('video', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('speciality', models.ManyToManyField(to='about.OurSpeciality')),
            ],
        ),
    ]
