# Generated by Django 4.0.2 on 2022-02-16 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_ourspeciality_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('twitter', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('youtube', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.designation')),
            ],
        ),
    ]
