# Generated by Django 4.0.2 on 2022-02-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_teamheading'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamheading',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
