# Generated by Django 4.0.2 on 2022-02-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_teamheading_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250)),
                ('experince_year', models.PositiveIntegerField()),
                ('quotes', models.TextField(max_length=250)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
